name:                ch29
version:             0.1.0.0
github:              "bpaterni/ch29"
license:             BSD3
author:              "Brian Paterni"
maintainer:          "bpaterni@gmail.com"
copyright:           "2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            demo

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bpaterni/ch29#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  a04-01-mvar:
    main:                Main.hs
    source-dirs:         a04-01-mvar
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch29
  a05-01-sharing:
    main:                Main.hs
    source-dirs:         a05-01-sharing
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch29
  a06-01-ref-trans:
    main:                Main.hs
    source-dirs:         a06-01-ref-trans
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch29
    - random
  a07-01-io-func-app-monad:
    main:                Main.hs
    source-dirs:         a07-01-io-func-app-monad
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch29
    - random
  a07-02-nestedio:
    main:                Main.hs
    source-dirs:         a07-02-nestedio
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch29
    - random
    - time
  a08-01-mvar:
    main:                Main.hs
    source-dirs:         a08-01-mvar
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch29
  a08-02-mvar-unsafe:
    main:                Main.hs
    source-dirs:         a08-02-mvar-unsafe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch29
  a09-01-chapex-io-with-vigenere:
    main:                Main.hs
    source-dirs:         a09-01-chapex-io-with-vigenere
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch29
    - monad-loops

tests:
  ch29-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch29
