name:                ch28
version:             0.1.0.0
github:              "bpaterni/ch28"
license:             BSD3
author:              "Brian Paterni"
maintainer:          "bpaterni@gmail.com"
copyright:           "2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            demo

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bpaterni/ch28#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  app-a02-01-criterion-ex-exe:
    main:                Main.hs
    source-dirs:         app-a02-01-criterion-ex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - ch28
    - criterion
  app-a02-02-criterion-ex-exe:
    main:                Main.hs
    source-dirs:         app-a02-02-criterion-ex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - ch28
    - criterion
  app-a03-01-prof-ex-exe:
    main:                Main.hs
    source-dirs:         app-a03-01-prof-ex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
  app-a03-02-prof-heap-ex-exe:
    main:                Main.hs
    source-dirs:         app-a03-02-prof-heap-ex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
  app-a04-01-caf-01:
    main:                Main.hs
    source-dirs:         app-a04-01-caf-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
  app-a04-02-caf-02:
    main:                Main.hs
    source-dirs:         app-a04-02-caf-02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
  app-a04-03-caf-03:
    main:                Main.hs
    source-dirs:         app-a04-03-caf-03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
  app-a05-01-map-01:
    main:                Main.hs
    source-dirs:         app-a05-01-map-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - containers
    - criterion
  app-a05-02-set-01:
    main:                Main.hs
    source-dirs:         app-a05-02-set-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - containers
    - criterion
  app-a06-03-set-01:
    main:                Main.hs
    source-dirs:         app-a06-03-set-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - containers
    - criterion
  app-a07-01-seq-01:
    main:                Main.hs
    source-dirs:         app-a07-01-seq-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - containers
    - criterion
  app-a07-01-seq-02:
    main:                Main.hs
    source-dirs:         app-a07-01-seq-02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - containers
    - criterion
  app-a08-01-vector-01:
    main:                Main.hs
    source-dirs:         app-a08-01-vector-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - criterion
    - vector
  app-a08-02-vec-update-01:
    main:                Main.hs
    source-dirs:         app-a08-02-vec-update-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - criterion
    - vector
  app-a08-02-vec-update-02:
    main:                Main.hs
    source-dirs:         app-a08-02-vec-update-02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - criterion
    - vector
  app-a08-03-vec-mutable-01:
    main:                Main.hs
    source-dirs:         app-a08-03-vec-mutable-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - criterion
    - primitive
    - vector
  app-a08-04-vec-box-unbox-01:
    main:                Main.hs
    source-dirs:         app-a08-04-vec-box-unbox-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - criterion
    - vector
  app-a09-01-string-text-01:
    main:                Main.hs
    source-dirs:         app-a09-01-string-text-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - text
  app-a09-02-bytestring-01:
    main:                Main.hs
    source-dirs:         app-a09-02-bytestring-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - bytestring
    - text
    - zlib
  app-a09-03-char8bad-01:
    main:                Main.hs
    source-dirs:         app-a09-03-char8bad-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - bytestring
    - text
    - utf8-string
  app-a10-chapex-diff-list-01:
    main:                Main.hs
    source-dirs:         app-a10-chapex-diff-list-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - criterion
  app-a10-chapex-queue-01:
    main:                Main.hs
    source-dirs:         app-a10-chapex-queue-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
    - criterion

tests:
  ch28-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
