name:                ch28
version:             0.1.0.0
github:              "bpaterni/ch28"
license:             BSD3
author:              "Brian Paterni"
maintainer:          "bpaterni@gmail.com"
copyright:           "2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            demo

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bpaterni/ch28#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  app-a02-01-criterion-ex-exe:
    main:                Main.hs
    source-dirs:         app-a02-01-criterion-ex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - ch28
    - criterion
  app-a02-02-criterion-ex-exe:
    main:                Main.hs
    source-dirs:         app-a02-02-criterion-ex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - ch28
    - criterion
  app-a03-01-prof-ex-exe:
    main:                Main.hs
    source-dirs:         app-a03-01-prof-ex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
  app-a03-02-prof-heap-ex-exe:
    main:                Main.hs
    source-dirs:         app-a03-02-prof-heap-ex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28

tests:
  ch28-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch28
