name:                ch17
version:             0.1.0.0
github:              "bpaterni/ch17"
license:             BSD3
author:              "Brian Paterni"
maintainer:          "bpaterni@gmail.com"
copyright:           "2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            demo

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bpaterni/ch17#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ch17-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch17

tests:
  a02def-test:
    main:                A02.hs
    source-dirs:         test/a02def
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch17
