name:                ch26
version:             0.1.0.0
github:              "bpaterni/ch26"
license:             BSD3
author:              "Brian Paterni"
maintainer:          "bpaterni@gmail.com"
copyright:           "2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            demo

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bpaterni/ch26#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ch26-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch26
  mtrans-use-01-exe:
    main: Main.hs
    source-dirs: app-mtrans-use-01
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ch26
      - text
      - scotty
  mtrans-use-02-exe:
    main: Main.hs
    source-dirs: app-mtrans-use-02
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ch26
      - text
      - transformers
      - scotty
  etrans-use-01-exe:
    main: Main.hs
    source-dirs: app-etrans-use-01
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ch26
      - text
      - transformers
      - scotty
  etrans-use-02-exe:
    main: Main.hs
    source-dirs: app-etrans-use-02
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ch26
      - text
      - transformers
      - scotty

tests:
  a02-test:
    main:                A02.hs
    source-dirs:         test/a02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch26
    - transformers
  a04-test:
    main:                A04.hs
    source-dirs:         test/a04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch26
  a05-test:
    main:                A05.hs
    source-dirs:         test/a05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch26
  a08-test:
    main:                A08.hs
    source-dirs:         test/a08
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch26
    - transformers
  a09-test:
    main:                A09.hs
    source-dirs:         test/a09
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch26
    - transformers
    - scotty
    - text
  a10-test:
    main:                A10.hs
    source-dirs:         test/a10
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch26
    - transformers
  a14-test:
    main:                A14.hs
    source-dirs:         test/a14
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch26
    - transformers
