name:                ch30
version:             0.1.0.0
github:              "bpaterni/ch30"
license:             BSD3
author:              "Brian Paterni"
maintainer:          "bpaterni@gmail.com"
copyright:           "2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            demo

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bpaterni/ch30#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  a02-01-why-some-exc:
    main:                Main.hs
    source-dirs:         a02-01-why-some-exc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30
  a03-01-io-fail:
    main:                Main.hs
    source-dirs:         a03-01-io-fail
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30
  a04-01-try-either:
    main:                Main.hs
    source-dirs:         a04-01-try-either
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30
  a05-01-try-again:
    main:                Main.hs
    source-dirs:         a05-01-try-again
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30
  a05-02-party-stopper:
    main:                Main.hs
    source-dirs:         a05-02-party-stopper
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30
    - random
  a06-01-why-throwio:
    main:                Main.hs
    source-dirs:         a06-01-why-throwio
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30
  a07-01-own-exceptions:
    main:                Main.hs
    source-dirs:         a07-01-own-exceptions
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30
  a07-02-own-exceptions:
    main:                Main.hs
    source-dirs:         a07-02-own-exceptions
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30
  a08-01-bottom-surprises:
    main:                Main.hs
    source-dirs:         a08-01-bottom-surprises
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30
  a09-01-async-exceptions:
    main:                Main.hs
    source-dirs:         a09-01-async-exceptions
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30

tests:
  ch30-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch30
