name:                a0701commonfunctors
version:             0.1.0.0
github:              "bpaterni/a0701commonfunctors"
license:             BSD3
author:              "Brian Paterni"
maintainer:          "bpaterni@gmail.com"
copyright:           "2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            demo

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bpaterni/a0701commonfunctors#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - ReplaceExperiment

executables:
  a0701commonfunctors-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - a0701commonfunctors

tests:
  a0701commonfunctors-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - a0701commonfunctors
  funkshun-test:
    main: Funkshun.hs
    source-dirs: test/funkshun
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - a0701commonfunctors
  heavylifting-test:
    main: HeavyLifting.hs
    source-dirs: test/a03heavylifting
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - a0701commonfunctors
